"""set timetable optional

Revision ID: 9f791c98efa8
Revises: 66c2bc90e068
Create Date: 2025-09-30 10:03:13.751422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f791c98efa8'
down_revision: Union[str, Sequence[str], None] = '66c2bc90e068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'timetable_min',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('schedules', 'timetable_max',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'timetable_max',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedules', 'timetable_min',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
